### ISSUE TITLE
JS version?

### ISSUE THREAD

**Issue by Beelzebob6666** [coenvl/foe-anniversary#2]
Hi there,
I am one of the Devs working on FoE Helper.

In preparation for the upcoming soccer event (redo of anniversary) I tried to create a brute force solver myself but performance is unuseable at the moment for real time application. Especially, when there are a lot of key pieces on the board.

Is your py-version of the solver useable for realtime application? If so, how did you do it?

This is my JS version by the way:

`//Brute force Solver -- can be extremely slow 
	solveBF:() => {

		let solved = {}
		let cells={}
		let ocells=window.structuredClone(mergerGame.cells)//.sort((a,b)=>b.level-a.level)
		for (let x of ocells) {
			if (!x.id || x.id<1) continue;
			if (!cells[x.type.value]) cells[x.type.value] = [];
			cells[x.type.value].push(x)
		}

		for (let c in cells) {
			if (!cells[c]) continue
			cells[c] = window.structuredClone(cells[c].sort((a,b)=> a.locked == false?-1:1))
			solved[c] = mergerGame.solverBFStep(cells[c],mergerGame.solverBFeval(cells[c]))
			console.log ("%c=======Solver=======","background: lightgrey; color:"+c)
			for (let x of solved[c].path) {
				let advice=`Free L${cells[c][x.i].level} ${cells[c][x.i].keyType.value!="none"?cells[c][x.i].keyType.value + " ":""}`
				advice+=`+ ${cells[c][x.j].locked ? "Locked" : "Free"} L${cells[c][x.j].level} ${cells[c][x.j].keyType.value!="none"?cells[c][x.j].keyType.value:""}`
				console.log(advice);
				cells[c][x.i].level = cells[c][x.i].level <= 3 ? cells[c][x.i].level + 1 : 4;
				if ((cells[c][x.i].keyType.value=="bottom" && cells[c][x.j].keyType.value=="top") || cells[c][x.i].keyType.value=="full" || cells[c][x.j].keyType.value=="full")
					cells[c][x.i].keyType.value="full"
				else if (cells[c][x.i].keyType.value=="none")
					cells[c][x.i].keyType.value=cells[c][x.j].keyType.value;
				cells[c].splice(x.j,1);
			}
		}

		//[mergerGame.simKeys,mergerGame.simProgress] = mergerGame.simulate(solved);
	},

	solverBFStep:(cells, startvalue,path=[],minlevel=1)=> {
		let moves={};
		let bestpath=[];
		let bestresult={value:0,progress:0,keys:0};
		for (let i=0; i < cells.length-1; i++) {
			if (cells[i].locked) break;
			for (let j=i+1;j<cells.length;j++) {
				if (cells[i].level == cells[j].level && cells[i].level>=minlevel) {
					if (cells[j].keyType.value != "full" || cells[j].level != 4) {
						let key=""+cells[i].level+cells[i].keyType.value+cells[i].locked+cells[j].level+cells[j].keyType.value+cells[j].locked
						if (!moves[key]) moves[key]=({i:i,j:j})
					}

					
				}
			}
		}
		if (Object.keys(moves).length == 0) return {eval:mergerGame.solverBFeval(cells,startvalue),path:path}
		for (let xi of Object.keys(moves).sort()) {
			//if (!moves[xi]) continue
			let x = moves[xi];
			let newcells=window.structuredClone(cells);
			let newpath=window.structuredClone(path);
			let l = newcells[x.i].level
			newpath.push(x);
			newcells[x.i].level = newcells[x.i].level <= 3 ? newcells[x.i].level + 1 : 4;
			if ((newcells[x.i].keyType.value=="bottom" && newcells[x.j].keyType.value=="top") || newcells[x.i].keyType.value=="full" || newcells[x.j].keyType.value=="full")
				newcells[x.i].keyType.value="full"
			else if (newcells[x.i].keyType.value=="none")
				newcells[x.i].keyType.value=newcells[x.j].keyType.value;
			newcells.splice(x.j,1)
			let result = mergerGame.solverBFStep(newcells,startvalue,newpath,l)
			if (result.eval.value>bestresult.value) {
				bestpath = result.path;
				bestresult = result.eval;
			}
		}
		return {eval:bestresult,path:bestpath}
	},

	solverBFeval:(cells,startvalue=null) =>{
		let progress=0;
		let keys=0;
		for (let x of cells) {
			if (x.keyType.value =="full") keys += mergerGame.keyValues[x.level]
			if (x.locked) progress += mergerGame.levelValues[x.level]
		}
		if (startvalue) {
			progress = startvalue.progress - progress;
			keys -= startvalue.keys;
		}
		return {keys:keys,progress:progress,value:keys*mergerGame.settings.keyValue+progress}
	},
`

**Comment by coenvl** [comment]
Hi Beelzebob,

I recognize that performance can be quite challenging in creating a bruteforce solver. But yes I think this solver is useable for a realtime application for any realistic input. Of course, when the number of gems get really large the solver will slow down. In our testset, the most difficult problem "tc47" has 35 gems (total of locked and free gems), and takes almost a full second to solve on my laptop. 

About how I did it. Well, there are a couple of important aspects:

1. **Dynamic programming to search through all possible moves.** This is basically the function `Solver.solve` in solver.py#L227. Here I keep track of a list of potential game states, with their current score and their maximum potential score. Whenever a maximum potential score is lower than some other game state current score, this move can be discarded.
2. **Finding a good scoring function**. There are two parts to this, there is a current score based on the total number of keys, minus a penalty for any locked gems so we maximize progress, and a penalty for gems without any key parts to steer searching to gettings parts. As mentioned before there is also the maximum *potential* score, that takes the minimum of any key parts. This potential score is used to prune the search space.
3. **Prioritizing good moves**. This is basically `Solver._find_good_moves` in solver.py#L245. Currently it uses a method by Muche to prefer unlocking the lowest level gems.
4. **Encoding gems**. This is a bit of an optimization, but it really helped in speeding things up. In `Gem.__init__` on line solver.py#L27 I compute a hash gem based on its level, locked state and gem part to get unique integer for that type of gem.


I would need some more time to get a good look at your JavaScript version. From what I see right now is that you recursively try *every* possible move, is that correct? This is similar to what I do, but is indeed quite expensive. Disregarding any states that are useless, i.e that have a lower potential score than the current best actual score, should help quite a bit.

**Comment by Beelzebob6666** [comment]
"Disregarding any states that are useless, i.e that have a lower potential score than the current best actual score, should help quite a bit."
Yeah, that might be the key to shorten the times - will try to implement something like that.
Also cancel the search, when one path for max potential score is found seems proper.

Only the evaluation of the "max potential" does not seem quite that easy. currently thinking of something like:
- keys: min(number of free pieces, sum top, sum bottom)
- progress: min(free L1, locked L1) + min(max(free L1, locked L1) + min L2, locked L2) + min(...)

potential keys likely will need to exclude cases where the free pieces are higher level than the available locked pieces...
